export type ProductCategory = {
  slug: string
  name: string
  navLabel: string
  description: string
  image: string
}

export type FrozenGroup = 'chicken' | 'meat' | 'seafood' | 'breaded'

export type Product = {
  slug: string
  name: string
  categorySlug: string
  image: string
  gallery?: string[]
  brandSlug?: string
  packSize?: string
  origin?: string
  frozenGroup?: FrozenGroup
}

const img = (file: string) => `/Products/${file}`
const cat = (file: string) => img(`catalogue/${file}`)
const brandCat = (file: string) => `/brand/catalogue/${file}`

export const productCategories: ProductCategory[] = [
  {
    slug: 'pasta',
    name: 'Pasta',
    navLabel: 'Pasta',
    description: 'Pasta for retail, foodservice and private-label programmes.',
    image: img('penne_pasta_450gm_Packet_Zarella.png'),
  },
  {
    slug: 'sauces',
    name: 'Sauces & Ketchup',
    navLabel: 'Sauces',
    description: 'Sauces, ketchup and ready-to-use cooking sauces.',
    image: img('Pizza_Sause_American_Hat.png'),
  },
  {
    slug: 'oils',
    name: 'Oils',
    navLabel: 'Oils',
    description: 'Olive oil, edible oil and frying oil in retail and bulk formats.',
    image: img('Olive_Oil_4L_Tin_Zaitha.png'),
  },
  {
    slug: 'condiments',
    name: 'Condiments',
    navLabel: 'Condiments',
    description: 'Mayonnaise, mustard, vinegar and tahina.',
    image: img('Mayanoisse_American_Hat.png'),
  },
  {
    slug: 'dairy',
    name: 'Dairy',
    navLabel: 'Dairy',
    description: 'Milk powder, condensed and evaporated milk, cheese and flavoured cream.',
    image: img('Milk_Powder_2.5Kg_tin_American_Hat.png'),
  },
  {
    slug: 'grocery',
    name: 'Grocery',
    navLabel: 'Grocery',
    description: 'Beans, custard powder, honey, salt, rose water and canned sardines.',
    image: cat('dachi_chick_peas_400g.png'),
  },
  {
    slug: 'frozen',
    name: 'Frozen & Protein',
    navLabel: 'Frozen',
    description: 'Frozen chicken, meat, seafood and breaded or prepared lines for local trade, import and export under the Tash brand.',
    image: '/Products/frozen/frozen-products-intro.png',
  },
  {
    slug: 'non-food',
    name: 'Non-food / Disposables',
    navLabel: 'Non-food',
    description: 'Disposable products from Glorious Pack for foodservice, retail and institutional buyers Ã¢â‚¬â€ cling film, packaging consumables and everyday disposables built for hygiene and efficiency.',
    image: '/Products/non-food/Glory_Wrap_45cm_300m.png',
  },
  {
    slug: 'commodities',
    name: 'Commodities',
    navLabel: 'Commodities',
    description: 'Generic commodity trading with containerised exports Ã¢â‚¬â€ grains and related lines. Details coming soon.',
    image: '/Products/frozen/mixed-vegetables.png',
  },
  {
    slug: 'confectionery',
    name: 'Confectionery',
    navLabel: 'Confectionery',
    description: 'Confectionery programmes for trade partners. Catalogue details coming soon.',
    image: 'https://images.unsplash.com/photo-1511381939415-e44015466834?auto=format&fit=crop&w=1600&q=80',
  },
  {
    slug: 'beverages',
    name: 'Beverages & Juice Powders',
    navLabel: 'Beverages',
    description: 'Tea and beverage programmes for retail and foodservice distribution.',
    image: brandCat('black_tea_lifestyle.jpg'),
  },
]

export const homeCategories = [
  {
    slug: 'pasta',
    name: 'Pasta',
    href: '/products/pasta',
    image: img('penne_pasta_450gm_Packet_Zarella.png'),
  },
  {
    slug: 'sauces',
    name: 'Sauces',
    href: '/products/sauces',
    image: img('Pizza_Sause_American_Hat.png'),
  },
  {
    slug: 'olive-oil',
    name: 'Olive Oil',
    href: '/products/oils',
    image: img('Olive_Oil_4L_Tin_Zaitha.png'),
  },
  {
    slug: 'cooking-oil',
    name: 'Cooking Oil',
    href: '/products/oils',
    image: img('Frying_Oil_18L_American_Hat.png'),
  },
  {
    slug: 'mayonnaise',
    name: 'Mayonnaise',
    href: '/products/condiments',
    image: img('Mayanoisse_American_Hat.png'),
  },
  {
    slug: 'mustard',
    name: 'Mustard',
    href: '/products/condiments',
    image: img('Dijon_Mustard_1Kg_American_Hat.png'),
  },
  {
    slug: 'vinegar',
    name: 'Vinegar',
    href: '/products/condiments',
    image: img('Vinegar_1USGallon_Bottle_American_Hat.png'),
  },
  {
    slug: 'dairy',
    name: 'Dairy',
    href: '/products/dairy',
    image: img('Milk_Powder_2.5Kg_tin_American_Hat.png'),
  },
  {
    slug: 'cheese',
    name: 'Cheese',
    href: '/products/dairy',
    image: img('Mozerella_Cheese_2Kg_American_Hat.png'),
  },
  {
    slug: 'seafood',
    name: 'Seafood',
    href: '/products/grocery',
    image: img('Sardines_in_sunflower_oil_125gm_box_American_Hat.png'),
  },
]

export const products: Product[] = [
  {
    slug: 'penne-pastx450g',
    name: 'Penne Pasta',
    categorySlug: 'pasta',
    brandSlug: 'zarella',
    packSize: '450g packet',
    image: img('penne_pasta_450gm_Packet_Zarella.png'),
  },
  {
    slug: 'rigatoni-pastx400g',
    name: 'Rigatoni Pasta',
    categorySlug: 'pasta',
    brandSlug: 'zarella',
    packSize: '400g',
    image: img('Rigatoni_Pasta_400gm_zarella.png'),
  },
  {
    slug: 'macaroni-pastx400g',
    name: 'Macaroni Pasta',
    categorySlug: 'pasta',
    brandSlug: 'zarella',
    packSize: '400g',
    image: img('Macaroni_Pasta_400gm_Zarella.png'),
  },
  {
    slug: 'vermicelli-450g',
    name: 'Vermicelli',
    categorySlug: 'pasta',
    brandSlug: 'zarella',
    packSize: '450g',
    image: img('Vermicelli_450gm_Zarella.png'),
  },
  {
    slug: 'tomato-ketchup-340g',
    name: 'Tomato Ketchup',
    categorySlug: 'sauces',
    brandSlug: 'american-hat',
    packSize: '340g bottle',
    image: img('Tomato_Ketchup_340gm_bottle_American_Hat.png'),
  },
  {
    slug: 'tomato-ketchup-5kg',
    name: 'Tomato Ketchup',
    categorySlug: 'sauces',
    brandSlug: 'tash',
    packSize: '5kg',
    image: img('Tomato_Ketchup_5KG_Tash_Brand.png'),
  },
  {
    slug: 'hot-chilli-sauce',
    name: 'Hot Chilli Sauce',
    categorySlug: 'sauces',
    brandSlug: 'american-hat',
    image: img('Hot_Chilli_Sauce_American_Hat.png'),
  },
  {
    slug: 'bbq-sauce-510ml',
    name: 'BBQ Sauce',
    categorySlug: 'sauces',
    brandSlug: 'american-hat',
    packSize: '510ml',
    image: img('BBQ_Sauce_510ML_America_Hat.png'),
  },
  {
    slug: 'pastxsauce',
    name: 'Pasta Sauce',
    categorySlug: 'sauces',
    brandSlug: 'american-hat',
    image: img('Pasta_Sause_American_Hat.png'),
  },
  {
    slug: 'pizzxsauce',
    name: 'Pizza Sauce',
    categorySlug: 'sauces',
    brandSlug: 'american-hat',
    image: img('Pizza_Sause_American_Hat.png'),
    gallery: [img('Pizza_Sause_American_Hat.png')],
  },
  {
    slug: 'olive-oil-250ml',
    name: 'Olive Oil',
    categorySlug: 'oils',
    brandSlug: 'legacy-valley',
    packSize: '250ml bottle',
    image: img('Olive_Oil_250ml_bottle_Legacy_Valley.png'),
  },
  {
    slug: 'olive-oil-500ml',
    name: 'Olive Oil',
    categorySlug: 'oils',
    brandSlug: 'legacy-valley',
    packSize: '500ml bottle',
    image: img('Olive_Oil_500ml_bottle_Legacy_Valley.png'),
  },
  {
    slug: 'olive-oil-1l',
    name: 'Olive Oil',
    categorySlug: 'oils',
    brandSlug: 'legacy-valley',
    packSize: '1L bottle',
    image: img('Olive_Oil_1L_bottle_Legacy_Valley.png'),
  },
  {
    slug: 'olive-oil-4l-legacy-valley',
    name: 'Olive Oil',
    categorySlug: 'oils',
    brandSlug: 'legacy-valley',
    packSize: '4L tin',
    image: img('Olive_Oil_4L_Tin_Legacy_Valley.png'),
  },
  {
    slug: 'olive-oil-4l-zaitha',
    name: 'Olive Oil',
    categorySlug: 'oils',
    brandSlug: 'zaitha',
    packSize: '4L tin',
    image: img('Olive_Oil_4L_Tin_Zaitha.png'),
  },
  {
    slug: 'edible-oil-17-5l',
    name: 'Edible Oil',
    categorySlug: 'oils',
    brandSlug: 'zaitha',
    packSize: '17.5L tin',
    image: img('Edible_Oil_17.5L_Tin_Zaitha.png'),
  },
  {
    slug: 'frying-oil-18l',
    name: 'Frying Oil',
    categorySlug: 'oils',
    brandSlug: 'american-hat',
    packSize: '18L',
    image: img('Frying_Oil_18L_American_Hat.png'),
  },
  {
    slug: 'classic-mayonnaise',
    name: 'Classic Mayonnaise',
    categorySlug: 'condiments',
    brandSlug: 'american-hat',
    packSize: 'Retail and foodservice formats',
    image: img('Mayanoisse_American_Hat.png'),
  },
  {
    slug: 'mayonnaise-5kg',
    name: 'Mayonnaise',
    categorySlug: 'condiments',
    brandSlug: 'american-hat',
    packSize: '5kg bucket',
    image: img('Mayonnaise_5KG_Bucket_American_Hat.png'),
  },
  {
    slug: 'dijon-mustard-1kg',
    name: 'Dijon Mustard',
    categorySlug: 'condiments',
    brandSlug: 'american-hat',
    packSize: '1kg',
    image: img('Dijon_Mustard_1Kg_American_Hat.png'),
    gallery: [img('Dijon_Mustard_1Kg_American_Hat_2.png')],
  },
  {
    slug: 'vinegar-1-us-gallon',
    name: 'Vinegar',
    categorySlug: 'condiments',
    brandSlug: 'american-hat',
    packSize: '1 US gallon bottle',
    image: img('Vinegar_1USGallon_Bottle_American_Hat.png'),
  },
  {
    slug: 'tahinx10kg',
    name: 'Tahina Sesame Paste',
    categorySlug: 'condiments',
    brandSlug: 'zaitha',
    packSize: '10kg tin',
    image: img('Tahina_Sesame_Paste_10KG_Tin_Zaitha.png'),
  },
  {
    slug: 'milk-powder-2-5kg',
    name: 'Milk Powder',
    categorySlug: 'dairy',
    brandSlug: 'american-hat',
    packSize: '2.5kg tin',
    image: img('Milk_Powder_2.5Kg_tin_American_Hat.png'),
    gallery: [
      img('Milk_Powder_2.5Kg_tin_American_Hat_2.png'),
      img('Milk_Powder_2.5Kg_tin_American_Hat_3.png'),
      img('Milk_Powder_2.5Kg_tin_American_Hat_4.png'),
    ],
  },
  {
    slug: 'condensed-milk-390g',
    name: 'Condensed Milk',
    categorySlug: 'dairy',
    brandSlug: 'american-hat',
    packSize: '390g',
    image: img('Condensed_Milk_390gm_American_Hat.png'),
  },
  {
    slug: 'evaporated-milk-410g',
    name: 'Evaporated Milk',
    categorySlug: 'dairy',
    brandSlug: 'american-hat',
    packSize: '410g tin',
    image: img('Evapourated_Milk_410gm_Tin_American_Hat.png'),
  },
  {
    slug: 'mozzarellxcheese-2kg',
    name: 'Mozzarella Cheese',
    categorySlug: 'dairy',
    brandSlug: 'american-hat',
    packSize: '2kg',
    image: img('Mozerella_Cheese_2Kg_American_Hat.png'),
  },
  {
    slug: 'cream-honey',
    name: 'Cream Ã¢â‚¬â€ Honey Flavour',
    categorySlug: 'dairy',
    brandSlug: 'tash',
    image: img('Cream_Honey_Flavour_Tash.png'),
  },
  {
    slug: 'cream-banana',
    name: 'Cream Ã¢â‚¬â€ Banana Flavour',
    categorySlug: 'dairy',
    brandSlug: 'tash',
    image: img('Cream_Banana_Flavour_Tash.png'),
  },
  {
    slug: 'cream-strawberry',
    name: 'Cream Ã¢â‚¬â€ Strawberry Flavour',
    categorySlug: 'dairy',
    brandSlug: 'tash',
    image: img('Cream_Strawberry_Flavour_Tash.png'),
  },
  {
    slug: 'custard-powder-200g',
    name: 'Custard Powder Ã¢â‚¬â€ Vanilla',
    categorySlug: 'grocery',
    brandSlug: 'american-hat',
    packSize: '200g',
    image: img('Custard_Powder_Vanilla_Flavour_200gm_American_Hat.png'),
  },
  {
    slug: 'rose-water',
    name: 'Rose Water',
    categorySlug: 'grocery',
    brandSlug: 'tash',
    image: img('Rose_Water_Tash.png'),
  },
  {
    slug: 'sardines-125g',
    name: 'Sardines in Sunflower Oil',
    categorySlug: 'grocery',
    brandSlug: 'american-hat',
    packSize: '125g',
    origin: 'Morocco',
    image: img('Sardines_in_sunflower_oil_125gm_box_American_Hat.png'),
    gallery: [
      img('Sardines_in_sunflower_oil_125gm_box_American_Hat_2.png'),
      img('Sardines_in_sunflower_oil_125gm_box_American_Hat_3.png'),
      img('Sardines_in_sunflower_oil_125gm_box_American_Hat_4.png'),
    ],
  },
  {
    slug: 'whole-chicken',
    name: 'Whole Chicken',
    categorySlug: 'frozen',
    frozenGroup: 'chicken',
    brandSlug: 'tash',
    image: '/Products/frozen/chicken-whole.png',
    packSize: 'Frozen',
  },
  {
    slug: 'chicken-leg-quarters',
    name: 'Chicken Leg Quarters',
    categorySlug: 'frozen',
    frozenGroup: 'chicken',
    brandSlug: 'tash',
    image: '/Products/frozen/chicken-legs.png',
    packSize: 'Frozen',
  },
  {
    slug: 'chicken-breast',
    name: 'Chicken Breast',
    categorySlug: 'frozen',
    frozenGroup: 'chicken',
    brandSlug: 'tash',
    image: '/Products/frozen/chicken-breast.png',
    packSize: 'Frozen',
  },
  {
    slug: 'chicken-wings',
    name: 'Chicken Wings',
    categorySlug: 'frozen',
    frozenGroup: 'chicken',
    brandSlug: 'tash',
    image: '/Products/frozen/chicken-wings.png',
    packSize: 'Frozen',
  },
  {
    slug: 'chicken-drumsticks',
    name: 'Chicken Drumsticks',
    categorySlug: 'frozen',
    frozenGroup: 'chicken',
    brandSlug: 'tash',
    image: '/Products/frozen/chicken-legs.png',
    packSize: 'Frozen',
  },
  {
    slug: 'indian-beef-cuts',
    name: 'Indian Beef Cuts',
    categorySlug: 'frozen',
    frozenGroup: 'meat',
    brandSlug: 'tash',
    image: '/Products/frozen/beef-cuts.png',
    packSize: 'Frozen',
  },
  {
    slug: 'mutton-cuts',
    name: 'Mutton / Lamb Cuts',
    categorySlug: 'frozen',
    frozenGroup: 'meat',
    brandSlug: 'tash',
    image: '/Products/frozen/mutton.png',
    packSize: 'Frozen',
  },
  {
    slug: 'beef-burger-patties',
    name: 'Beef Burger Patties',
    categorySlug: 'frozen',
    frozenGroup: 'meat',
    brandSlug: 'tash',
    image: '/Products/frozen/burger-patties.png',
    packSize: 'Frozen',
  },
  {
    slug: 'chicken-nuggets',
    name: 'Chicken Nuggets',
    categorySlug: 'frozen',
    frozenGroup: 'breaded',
    brandSlug: 'tash',
    image: '/Products/frozen/chicken-nuggets.png',
    packSize: 'Frozen',
  },
  {
    slug: 'sausages',
    name: 'Sausages',
    categorySlug: 'frozen',
    frozenGroup: 'meat',
    brandSlug: 'tash',
    image: '/Products/frozen/sausages.png',
    packSize: 'Frozen',
  },
  {
    slug: 'frozen-mixed-vegetables',
    name: 'Frozen Mixed Vegetables',
    categorySlug: 'frozen',
    frozenGroup: 'breaded',
    brandSlug: 'tash',
    image: '/Products/frozen/mixed-vegetables.png',
    packSize: 'Frozen',
  },
  {
    slug: 'french-fries',
    name: 'French Fries',
    categorySlug: 'frozen',
    frozenGroup: 'breaded',
    brandSlug: 'tash',
    image: '/Products/frozen/frozen-fries.png',
    packSize: 'Frozen',
  },
  {
    slug: 'fish-fillets',
    name: 'Fish Fillets',
    categorySlug: 'frozen',
    frozenGroup: 'seafood',
    brandSlug: 'tash',
    image: '/Products/frozen/fish-fillet.png',
    packSize: 'Frozen',
  },
  {
    slug: 'minced-meat',
    name: 'Minced Beef / Chicken',
    categorySlug: 'frozen',
    frozenGroup: 'meat',
    brandSlug: 'tash',
    image: '/Products/frozen/beef-cuts.png',
    packSize: 'Frozen',
  },
  {
    slug: 'glory-wrap',
    name: 'Glory Wrap',
    categorySlug: 'non-food',
    brandSlug: 'glorious-pack',
    image: '/Products/non-food/Glory_Wrap_45cm_300m.png',
    packSize: '45cm Ãƒâ€” 300m',
  },
  {
    slug: 'disposable-plates',
    name: 'Disposable Plates',
    categorySlug: 'non-food',
    brandSlug: 'glorious-pack',
    image: '/Products/non-food/disposable-plates.png',
    packSize: 'Foodservice packs',
  },
  {
    slug: 'disposable-cups',
    name: 'Disposable Cups',
    categorySlug: 'non-food',
    brandSlug: 'glorious-pack',
    image: '/Products/non-food/disposable-cups.png',
    packSize: 'Foodservice packs',
  },
  {
    slug: 'disposable-glasses',
    name: 'Disposable Glasses',
    categorySlug: 'non-food',
    brandSlug: 'glorious-pack',
    image: '/Products/non-food/disposable-glasses.png',
    packSize: 'Foodservice packs',
  },
  {
    slug: 'disposable-cutlery',
    name: 'Disposable Cutlery',
    categorySlug: 'non-food',
    brandSlug: 'glorious-pack',
    image: '/Products/non-food/disposable-cutlery.png',
    packSize: 'Foodservice packs',
  },
  {
    slug: 'disposable-bowls',
    name: 'Disposable Bowls',
    categorySlug: 'non-food',
    brandSlug: 'glorious-pack',
    image: '/Products/non-food/disposable-bowls.png',
    packSize: 'Foodservice packs',
  },
  // --- Catalogue additions: Dachi beans ---
  {
    slug: 'dachi-chick-peas-400g',
    name: 'Chick Peas',
    categorySlug: 'grocery',
    brandSlug: 'dachi',
    packSize: '400g',
    image: cat('dachi_chick_peas_400g.png'),
  },
  {
    slug: 'dachi-red-kidney-beans-400g',
    name: 'Red Kidney Beans',
    categorySlug: 'grocery',
    brandSlug: 'dachi',
    packSize: '400g',
    image: cat('dachi_red_kidney_beans_400g.png'),
  },
  {
    slug: 'dachi-baked-beans-400g',
    name: 'Baked Beans',
    categorySlug: 'grocery',
    brandSlug: 'dachi',
    packSize: '400g',
    image: cat('dachi_baked_beans_400g.png'),
  },
  {
    slug: 'dachi-fava-beans-400g',
    name: 'Fava Beans',
    categorySlug: 'grocery',
    brandSlug: 'dachi',
    packSize: '400g',
    image: cat('dachi_fava_beans_400g.png'),
  },
  // --- Zarella extra shapes ---
  {
    slug: 'zarella-fusilli-400g',
    name: 'Fusilli Pasta',
    categorySlug: 'pasta',
    brandSlug: 'zarella',
    packSize: '400g',
    origin: 'Italy',
    image: cat('zarella_fusilli_400g.png'),
  },
  {
    slug: 'zarella-conchiglie-400g',
    name: 'Conchiglie Pasta',
    categorySlug: 'pasta',
    brandSlug: 'zarella',
    packSize: '400g',
    origin: 'Italy',
    image: cat('zarella_conchiglie_400g.png'),
  },
  // --- Delicia pasta ---
  {
    slug: 'delicia-spaghetti-500g',
    name: 'Spaghetti',
    categorySlug: 'pasta',
    brandSlug: 'delicia',
    packSize: '500g',
    origin: 'Italy',
    image: cat('delicia_spaghetti_500g.png'),
  },
  {
    slug: 'delicia-elbow-500g',
    name: 'Elbow Pasta',
    categorySlug: 'pasta',
    brandSlug: 'delicia',
    packSize: '500g',
    origin: 'Italy',
    image: cat('delicia_elbow_500g.png'),
  },
  {
    slug: 'delicia-penne-500g',
    name: 'Penne Pasta',
    categorySlug: 'pasta',
    brandSlug: 'delicia',
    packSize: '500g',
    origin: 'Italy',
    image: cat('delicia_penne_500g.png'),
  },
  {
    slug: 'delicia-vermicelli-500g',
    name: 'Vermicelli',
    categorySlug: 'pasta',
    brandSlug: 'delicia',
    packSize: '500g',
    origin: 'Italy',
    image: cat('delicia_vermicelli_500g.png'),
  },
  {
    slug: 'delicia-fusilli-500g',
    name: 'Fusilli Pasta',
    categorySlug: 'pasta',
    brandSlug: 'delicia',
    packSize: '500g',
    origin: 'Italy',
    image: cat('delicia_fusilli_500g.png'),
  },
  // --- American Hat sauces ---
  {
    slug: 'sweet-chilli-sauce-710ml',
    name: 'Sweet Chilli Sauce',
    categorySlug: 'sauces',
    brandSlug: 'american-hat',
    packSize: '710ml',
    image: cat('american_hat_sweet_chilli_710ml.png'),
  },
  {
    slug: 'sriracha-sauce-482ml',
    name: 'Sriracha Sauce',
    categorySlug: 'sauces',
    brandSlug: 'american-hat',
    packSize: '482ml',
    image: cat('american_hat_sriracha_482ml.png'),
  },
  {
    slug: 'tomato-ketchup-5kg-american-hat',
    name: 'Tomato Ketchup',
    categorySlug: 'sauces',
    brandSlug: 'american-hat',
    packSize: '5kg',
    image: cat('american_hat_tomato_ketchup_5kg.png'),
  },
  // --- Zaitha / American Hat oils ---
  {
    slug: 'zaitha-olive-oil-5l',
    name: 'Extra Virgin Olive Oil',
    categorySlug: 'oils',
    brandSlug: 'zaitha',
    packSize: '5L',
    origin: 'Spain',
    image: cat('zaitha_olive_oil_5l.png'),
  },
  {
    slug: 'zaitha-olive-oil-1l',
    name: 'Extra Virgin Olive Oil',
    categorySlug: 'oils',
    brandSlug: 'zaitha',
    packSize: '1L',
    origin: 'Spain',
    image: cat('zaitha_olive_oil_1l.png'),
  },
  {
    slug: 'zaitha-olive-oil-500ml',
    name: 'Extra Virgin Olive Oil',
    categorySlug: 'oils',
    brandSlug: 'zaitha',
    packSize: '500ml',
    origin: 'Spain',
    image: cat('zaitha_olive_oil_500ml.png'),
  },
  {
    slug: 'zaitha-olive-oil-250ml',
    name: 'Extra Virgin Olive Oil',
    categorySlug: 'oils',
    brandSlug: 'zaitha',
    packSize: '250ml',
    origin: 'Spain',
    image: cat('zaitha_olive_oil_250ml.png'),
  },
  {
    slug: 'american-hat-olive-oil-5l',
    name: 'Spanish Extra Virgin Olive Oil',
    categorySlug: 'oils',
    brandSlug: 'american-hat',
    packSize: '5L',
    origin: 'Spain',
    image: cat('american_hat_olive_oil_5l.png'),
  },
  {
    slug: 'american-hat-olive-oil-4l',
    name: 'Spanish Extra Virgin Olive Oil',
    categorySlug: 'oils',
    brandSlug: 'american-hat',
    packSize: '4L',
    origin: 'Spain',
    image: cat('american_hat_olive_oil_4l.png'),
  },
  {
    slug: 'american-hat-olive-oil-1l',
    name: 'Spanish Extra Virgin Olive Oil',
    categorySlug: 'oils',
    brandSlug: 'american-hat',
    packSize: '1L bottle',
    origin: 'Spain',
    image: cat('american_hat_olive_oil_1l_bottle.png'),
  },
  {
    slug: 'american-hat-olive-oil-500ml',
    name: 'Spanish Extra Virgin Olive Oil',
    categorySlug: 'oils',
    brandSlug: 'american-hat',
    packSize: '500ml',
    origin: 'Spain',
    image: cat('american_hat_olive_oil_500ml.png'),
  },
  {
    slug: 'cooking-oil-1l',
    name: 'Vegetable Cooking Oil',
    categorySlug: 'oils',
    brandSlug: 'american-hat',
    packSize: '1L',
    origin: 'UAE',
    image: cat('cooking_oil_1l_pet.png'),
  },
  {
    slug: 'cooking-oil-1-8l',
    name: 'Vegetable Cooking Oil',
    categorySlug: 'oils',
    brandSlug: 'american-hat',
    packSize: '1.8L',
    origin: 'UAE',
    image: cat('cooking_oil_1_8l.png'),
  },
  {
    slug: 'cooking-oil-5l',
    name: 'Vegetable Cooking Oil',
    categorySlug: 'oils',
    brandSlug: 'american-hat',
    packSize: '5L',
    origin: 'UAE',
    image: cat('cooking_oil_5l.png'),
  },
  // --- Condiments extras ---
  {
    slug: 'mayonnaise-8oz',
    name: 'Classic Mayonnaise',
    categorySlug: 'condiments',
    brandSlug: 'american-hat',
    packSize: '8oz / 227ml',
    origin: 'UAE',
    image: cat('american_hat_mayonnaise_8oz.png'),
  },
  {
    slug: 'mayonnaise-16oz',
    name: 'Classic Mayonnaise',
    categorySlug: 'condiments',
    brandSlug: 'american-hat',
    packSize: '16oz / 473ml',
    origin: 'UAE',
    image: cat('american_hat_mayonnaise_16oz.png'),
  },
  {
    slug: 'mayonnaise-32oz',
    name: 'Classic Mayonnaise',
    categorySlug: 'condiments',
    brandSlug: 'american-hat',
    packSize: '32oz / 946ml',
    origin: 'UAE',
    image: cat('american_hat_mayonnaise_32oz.png'),
  },
  {
    slug: 'yellow-mustard-227g',
    name: 'Yellow Mustard',
    categorySlug: 'condiments',
    brandSlug: 'american-hat',
    packSize: '8oz / 227g',
    image: cat('american_hat_yellow_mustard_227g.png'),
  },
  {
    slug: 'yellow-mustard-3-78l',
    name: 'Yellow Mustard',
    categorySlug: 'condiments',
    brandSlug: 'american-hat',
    packSize: '3.78L',
    image: cat('american_hat_yellow_mustard_3_78l.png'),
  },
  {
    slug: 'white-vinegar-946ml',
    name: 'White Vinegar',
    categorySlug: 'condiments',
    brandSlug: 'american-hat',
    packSize: '946ml',
    origin: 'UAE',
    image: cat('american_hat_white_vinegar_946ml.png'),
  },
  {
    slug: 'white-vinegar-473ml',
    name: 'White Vinegar',
    categorySlug: 'condiments',
    brandSlug: 'american-hat',
    packSize: '473ml',
    origin: 'UAE',
    image: cat('american_hat_white_vinegar_473ml.png'),
  },
  // --- Grocery: honey, salt ---
  {
    slug: 'honey-340g',
    name: 'Honey',
    categorySlug: 'grocery',
    brandSlug: 'american-hat',
    packSize: '340g',
    origin: 'UAE',
    image: cat('american_hat_honey_340g.png'),
  },
  {
    slug: 'honey-500g',
    name: 'Honey',
    categorySlug: 'grocery',
    brandSlug: 'american-hat',
    packSize: '500g',
    origin: 'UAE',
    image: cat('american_hat_honey_500g.png'),
  },
  {
    slug: 'honey-1kg',
    name: 'Honey',
    categorySlug: 'grocery',
    brandSlug: 'american-hat',
    packSize: '1kg',
    origin: 'UAE',
    image: cat('american_hat_honey_1kg.png'),
  },
  {
    slug: 'iodized-salt-700g',
    name: 'Iodized Salt',
    categorySlug: 'grocery',
    brandSlug: 'american-hat',
    packSize: '700g',
    origin: 'UAE',
    image: cat('american_hat_iodized_salt_700g.png'),
  },
  {
    slug: 'iodized-salt-500g',
    name: 'Iodized Salt',
    categorySlug: 'grocery',
    brandSlug: 'american-hat',
    packSize: '500g',
    origin: 'UAE',
    image: cat('american_hat_iodized_salt_500g.png'),
  },
  {
    slug: 'iodized-salt-1kg',
    name: 'Iodized Salt',
    categorySlug: 'grocery',
    brandSlug: 'american-hat',
    packSize: '1kg',
    origin: 'UAE',
    image: cat('american_hat_iodized_salt_1kg.png'),
  },
  // --- Beverages: tea ---
  {
    slug: 'black-tea-100bags',
    name: 'Black Tea',
    categorySlug: 'beverages',
    brandSlug: 'american-hat',
    packSize: '100 tea bags',
    origin: 'India',
    image: cat('american_hat_black_tea_100bags.png'),
  },
  {
    slug: 'black-tea-500g',
    name: 'Black Tea',
    categorySlug: 'beverages',
    brandSlug: 'american-hat',
    packSize: '500g',
    origin: 'India',
    image: cat('american_hat_black_tea_500g.png'),
  },
  {
    slug: 'black-tea-1kg',
    name: 'Black Tea',
    categorySlug: 'beverages',
    brandSlug: 'american-hat',
    packSize: '1kg',
    origin: 'India',
    image: cat('american_hat_black_tea_1kg.png'),
  },
  {
    slug: 'green-tea-100bags',
    name: 'Green Tea',
    categorySlug: 'beverages',
    brandSlug: 'american-hat',
    packSize: '100 bags',
    origin: 'India',
    image: cat('american_hat_green_tea_100bags.png'),
  },
  {
    slug: 'lemon-green-tea-100bags',
    name: 'Lemon Green Tea',
    categorySlug: 'beverages',
    brandSlug: 'american-hat',
    packSize: '100 bags',
    origin: 'India',
    image: cat('american_hat_lemon_green_tea_100bags.png'),
  },
  {
    slug: 'mint-green-tea-100bags',
    name: 'Mint Green Tea',
    categorySlug: 'beverages',
    brandSlug: 'american-hat',
    packSize: '100 bags',
    origin: 'India',
    image: cat('american_hat_mint_green_tea_100bags.png'),
  },

]


export const frozenSections = [
  {
    id: 'chicken' as const,
    title: 'Chicken',
    eyebrow: 'Poultry',
    copy: 'Whole birds and cut chicken for retail, foodservice and export — frozen for consistent quality and dependable lead times under the Tash programme.',
    image: '/Products/frozen/chicken-whole.png',
  },
  {
    id: 'meat' as const,
    title: 'Meat',
    eyebrow: 'Red meat & processed',
    copy: 'Beef, lamb and processed meat lines including cuts, mince, burger patties and sausages for wholesale and foodservice partners.',
    image: '/Products/frozen/beef-cuts.png',
  },
  {
    id: 'seafood' as const,
    title: 'Seafood',
    eyebrow: 'Fish',
    copy: 'Frozen fish fillets for trade partners who need reliable seafood alongside poultry and meat in one cold-chain conversation.',
    image: '/Products/frozen/fish-fillet.png',
  },
  {
    id: 'breaded' as const,
    title: 'Breaded items',
    eyebrow: 'Coated & prepared',
    copy: 'Breaded proteins and prepared frozen sides — chicken nuggets, french fries and mixed vegetables for kitchens that need speed and consistency.',
    image: '/Products/frozen/chicken-nuggets.png',
  },
]

export function getFrozenProductsByGroup(group: FrozenGroup) {
  return products.filter((product) => product.categorySlug === 'frozen' && product.frozenGroup === group)
}

export const allProductNames = [...new Set(products.map((product) => product.name))]

export function getCategory(slug: string) {
  return productCategories.find((category) => category.slug === slug)
}

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug)
}

export function getProductsByCategory(slug: string) {
  return products.filter((product) => product.categorySlug === slug)
}

export function getRelatedProducts(product: Product, limit = 3) {
  const same = products.filter(
    (item) => item.categorySlug === product.categorySlug && item.slug !== product.slug,
  )
  const rest = products.filter(
    (item) => item.slug !== product.slug && item.categorySlug !== product.categorySlug,
  )
  return [...same, ...rest].slice(0, limit)
}

export function productHref(product: Product) {
  return `/products/${product.categorySlug}/${product.slug}`
}

export function productImage(product: Product) {
  return product.image
}

export function productGallery(product: Product) {
  return [product.image, ...(product.gallery ?? [])]
}

